version: 2
updates:
  - package-ecosystem: pip
    directory: "/apm-agent-backend"
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directory: "/rag-system"
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directory: "/rfi-automation"
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: "/procore-mcp-gateway"
    schedule: { interval: weekly }
